---
abstract: 'Iterative, recursive file finder'
author:
  - 'David Golden <dagolden@cpan.org>'
build_requires:
  Config: 0
  Exporter: 0
  ExtUtils::MakeMaker: 0
  File::Find: 0
  File::Spec::Functions: 0
  File::Temp: 0
  File::pushd: 0
  Path::Tiny: 0
  Test::Deep: 0
  Test::Filename: 0.03
  Test::More: 0.92
  autodie: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300030, CPAN::Meta::Converter version 2.120921'
license: apache
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Path-Iterator-Rule
no_index:
  directory:
    - t
    - xt
    - examples
    - corpus
  package:
    - DB
provides:
  PIR:
    file: lib/PIR.pm
    version: 1.003
  Path::Iterator::Rule:
    file: lib/Path/Iterator/Rule.pm
    version: 1.003
requires:
  Carp: 0
  Data::Clone: 0
  File::Basename: 0
  File::Spec: 0
  List::Util: 0
  Number::Compare: 0.02
  Scalar::Util: 0
  Text::Glob: 0
  Try::Tiny: 0
  namespace::clean: 0
  perl: 5.010
  re: 0
  strict: 0
  warnings: 0
  warnings::register: 0
resources:
  bugtracker: https://github.com/dagolden/path-iterator-rule/issues
  homepage: https://metacpan.org/release/Path-Iterator-Rule
  repository: git://github.com/dagolden/path-iterator-rule.git
version: 1.003
x_contributors:
  - 'Graham Knop <haarg@haarg.org>'
